authentication/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('create_post', views.create_post_view, name='create_post'),
    path('delete_post/<int:post_id>', views.delete_post_view, name='delete_post'),
    path('create_comment/<int:post_id>', views.create_comment_view, name='create_comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment_view, name='delete_comment'),
]

authentication/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.body


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    body = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.body

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


def login_view(request):

    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/')
        else:
            return render(request, "login.html")

    elif request.method == 'POST':
        user = authenticate(
            request,
            username=request.POST.get("username"),
            password=request.POST.get("password")
        )

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return redirect('/')


def logout_view(request):

    if request.user.is_authenticated:
        logout(request)
        return redirect('/')
    else:
        return redirect('/')

posts/views.py
from django.shortcuts import render, redirect

from .models import Post, Comment


def index_view(request):
    
    posts = Post.objects.all()
    context = {'posts': posts}

    return render(request, "posts.html", context)


def create_post_view(request):

    if request.method == 'POST':

        Post.objects.create(
            owner=request.user,
            body=request.POST.get("body")
        )

    return redirect('/')


def delete_post_view(request, post_id):

    if request.method == 'POST':

        post = Post.objects.get(id=post_id)

        if post.owner == request.user:

            post.delete()

    return redirect('/')


def create_comment_view(request, post_id):

    if request.method == 'POST':

        post = Post.objects.get(id=post_id)

        Comment.objects.create(
            owner=request.user,
            post=post,
            body=request.POST.get("body")
        )

    return redirect('/')


def delete_comment_view(request, comment_id):

    if request.method == 'POST':

        comment = Comment.objects.get(id=comment_id)

        if comment.owner == request.user:

            comment.delete()

    return redirect('/')

posts/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Blog</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="logout">Deslogar <span class="sr-only">(current)</span></a>
                    {% else %}
                        <a class="nav-link" href="login">Efetuar login <span class="sr-only">(current)</span></a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <br/>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <form method="POST" action="login">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Nome de usuáro</label>
                    <input type="text" class="form-control" id="id_username" name="username">
                </div>
                <div class="form-group">
                    <label for="id_password">Senha</label>
                    <input type="password" class="form-control" id="id_password" name="password">
                </div>
                <button type="submit" class="btn btn-primary">Efetuar login</button>
            </form>
        </div>
    </div>

{% endblock %}

posts/templates/posts.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-12">
                <h5 class="text-center">Escrever post</h5>

                <form method="POST" action="create_post">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="body" id="id_body" maxlength="200" required rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
        </div>
        <br>
    {% endif %}


    <div class="row">
        <div class="col-12">
            <h5 class="text-center">Posts</h5>
        </div>
    </div>

    {% if posts %}
        {% for post in posts %}
            <div class="row">
                <div class="offset-2 col-8">
                    <div class="card">
                        <div class="card-header text-center">
                            <b>
                                {% if post.owner.get_full_name %}
                                    {{ post.owner.get_full_name }}
                                {% else %}
                                    {{ post.owner.username }}
                                {% endif %}
                            </b>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                {{ post.body }}
                            </p>
                            <div class="d-flex justify-content-between">
                                <div>
                                    {% if post.owner == user %}
                                        <form method="POST" action="delete_post/{{ post.id }}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger">Apagar post</button>
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="text-muted">
                                    Comentários: {{ post.comments.count }}
                                </div>
                            </div>
                            {% if post.comments or user.is_authenticated %}
                                <hr>
                            {% endif %}
                            {% if post.comments %}
                                <p>Comentários:</p>
                                {% for comment in post.comments.all %}
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="card">
                                                <div class="card-body">
                                                        <b>
                                                            {% if comment.owner.get_full_name %}
                                                                {{ comment.owner.get_full_name }}
                                                            {% else %}
                                                                {{ comment.owner.username }}
                                                            {% endif %}
                                                        </b>
                                                    <p class="card-text">
                                                        {{ comment.body }}
                                                    </p>
                                                    <div class="d-flex justify-content-between">
                                                        <div>
                                                            {% if comment.owner == user %}
                                                                <form method="POST" action="delete_comment/{{ comment.id }}">
                                                                    {% csrf_token %}
                                                                    <button type="submit" class="btn btn-danger">Apagar comentário</button>
                                                                </form>
                                                            {% endif %}
                                                        </div>
                                                        <small class="text-muted">
                                                            Comentário feito em {{ comment.created_at }}
                                                        </small>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                {% endfor %}
                            {% endif %}
                            {% if user.is_authenticated %}
                                <div class="row">
                                    <div class="col-12">
                                        <form method="POST" action="create_comment/{{ post.id }}">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label for="id_body">Escrever comentário</label>
                                                <textarea class="form-control" name="body" id="id_body" maxlength="200" required rows="3"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Enviar</button>
                                        </form>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class="card-footer text-muted">
                            <small>Post feito em {{ post.created_at }}</small>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-12">
                <p>Não existem posts.</p>
            </div>
        </div>
    {% endif %}
{% endblock %}